### PR TITLE
tyding format

### PR DESCRIPTION
**Pull request by wishmouse**
tidying format

### CODE REVIEW

**Comment by joseph-code-EDA** [comment]
Line 55 : closing div tag has a < missing

**Comment by JamesANZ** [comment]
Line 26-29 Div Element should be indented

**Comment by wishmouse** [comment]
@joseph-code-EDA @James-Sangalli 
Changes made.

**Comment by JamesANZ** [comment]
Nice! looks mostly good however the following lines should be indented: 

77-102 , 123, 150-154

**Pull request merged**
